package com.cskaoyan.dao;

import com.cskaoyan.bean.Admin;

import java.util.HashMap;

public interface AdminMapper {


    Admin getAdminByUserNameAndPassword(HashMap<String, String> loginInfo);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Tue Apr 10 19:01:26 CST 2018
     */
    int deleteByPrimaryKey(Integer adminid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Tue Apr 10 19:01:26 CST 2018
     */
    int insert(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Tue Apr 10 19:01:26 CST 2018
     */
    int insertSelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Tue Apr 10 19:01:26 CST 2018
     */
    Admin selectByPrimaryKey(Integer adminid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Tue Apr 10 19:01:26 CST 2018
     */
    int updateByPrimaryKeySelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Tue Apr 10 19:01:26 CST 2018
     */
    int updateByPrimaryKey(Admin record);
}