package com.cskaoyan.dao;

import com.cskaoyan.bean.Commoditymeasurement;

public interface CommoditymeasurementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commoditymeasurement
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    int deleteByPrimaryKey(Integer commoditymeasurementid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commoditymeasurement
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    int insert(Commoditymeasurement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commoditymeasurement
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    int insertSelective(Commoditymeasurement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commoditymeasurement
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    Commoditymeasurement selectByPrimaryKey(Integer commoditymeasurementid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commoditymeasurement
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    int updateByPrimaryKeySelective(Commoditymeasurement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commoditymeasurement
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    int updateByPrimaryKey(Commoditymeasurement record);
}