package com.cskaoyan.dao;

import com.cskaoyan.bean.Commoditytype;

import java.util.ArrayList;

public interface CommoditytypeMapper {
    ArrayList<Commoditytype> getAllCommoditytype();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commoditytype
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    int deleteByPrimaryKey(Integer commoditytypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commoditytype
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    int insert(Commoditytype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commoditytype
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    int insertSelective(Commoditytype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commoditytype
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    Commoditytype selectByPrimaryKey(Integer commoditytypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commoditytype
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    int updateByPrimaryKeySelective(Commoditytype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commoditytype
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    int updateByPrimaryKey(Commoditytype record);
}