package com.cskaoyan.dao;

import com.cskaoyan.bean.Financialstatistics;

public interface FinancialstatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financialstatistics
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    int insert(Financialstatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financialstatistics
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    int insertSelective(Financialstatistics record);
}