package com.cskaoyan.dao;

import com.cskaoyan.bean.Ordcheckinpassenger;

public interface OrdcheckinpassengerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordcheckinpassenger
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordcheckinpassenger
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    int insert(Ordcheckinpassenger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordcheckinpassenger
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    int insertSelective(Ordcheckinpassenger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordcheckinpassenger
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    Ordcheckinpassenger selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordcheckinpassenger
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    int updateByPrimaryKeySelective(Ordcheckinpassenger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordcheckinpassenger
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    int updateByPrimaryKey(Ordcheckinpassenger record);
}