package com.cskaoyan.dao;

import com.cskaoyan.bean.Orderpayment;

import java.util.ArrayList;

public interface OrderpaymentMapper {

    ArrayList<Orderpayment> getAllOrderPayment();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderpayment
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    int insert(Orderpayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderpayment
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    int insertSelective(Orderpayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderpayment
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    Orderpayment selectByPrimaryKey(Integer far_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderpayment
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    int updateByPrimaryKeySelective(Orderpayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderpayment
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    int updateByPrimaryKey(Orderpayment record);
}