package com.cskaoyan.dao;

import com.cskaoyan.bean.Ordermain;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import java.util.HashMap;
import java.util.List;

public interface OrdermainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordermain
     *
     * @mbg.generated Thu Apr 12 17:56:44 CST 2018
     */
    int insert(Ordermain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordermain
     *
     * @mbg.generated Thu Apr 12 17:56:44 CST 2018
     */
    int insertSelective(Ordermain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordermain
     *
     * @mbg.generated Thu Apr 12 17:56:44 CST 2018
     */
    Ordermain selectByPrimaryKey(String ordID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordermain
     *
     * @mbg.generated Thu Apr 12 17:56:44 CST 2018
     */
    int updateByPrimaryKeySelective(Ordermain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordermain
     *
     * @mbg.generated Thu Apr 12 17:56:44 CST 2018
     */
    int updateByPrimaryKey(Ordermain record);

    List<Ordermain> selectAllOrderIsBeBooking();

    /**
    *修改订单状态为未结账
     */
    @Update("update ordermain set state=68")
    int modifyOrderStatus();

    @Select("select count(*) from ordermain ")
    int findAllOrderCount();

     List<Ordermain> findPartOrder(HashMap<String, Object> map) ;

}