package com.cskaoyan.dao;

import com.cskaoyan.bean.Orderpayment;
import org.apache.ibatis.annotations.Select;

import java.util.ArrayList;

public interface OrderpaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderpayment
     *
     * @mbg.generated Thu Apr 12 16:36:05 CST 2018
     */
    int insert(Orderpayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderpayment
     *
     * @mbg.generated Thu Apr 12 16:36:05 CST 2018
     */
    int insertSelective(Orderpayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderpayment
     *
     * @mbg.generated Thu Apr 12 16:36:05 CST 2018
     */
    Orderpayment selectByPrimaryKey(Integer far_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderpayment
     *
     * @mbg.generated Thu Apr 12 16:36:05 CST 2018
     */
    int updateByPrimaryKeySelective(Orderpayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderpayment
     *
     * @mbg.generated Thu Apr 12 16:36:05 CST 2018
     */
    int updateByPrimaryKey(Orderpayment record);

    //@Select("select * from orderpayment where del_flag=0")
    ArrayList<Orderpayment> getAllOrderPayment();
}