package com.cskaoyan.dao;

import com.cskaoyan.bean.Orderpayment;

public interface OrderpaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderpayment
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    int deleteByPrimaryKey(Integer orderpaymentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderpayment
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    int insert(Orderpayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderpayment
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    int insertSelective(Orderpayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderpayment
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    Orderpayment selectByPrimaryKey(Integer orderpaymentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderpayment
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    int updateByPrimaryKeySelective(Orderpayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderpayment
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    int updateByPrimaryKey(Orderpayment record);
}