package com.cskaoyan.dao;

import com.cskaoyan.bean.Passengerdegree;

public interface PassengerdegreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passengerdegree
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    int insert(Passengerdegree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passengerdegree
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    int insertSelective(Passengerdegree record);
}