package com.cskaoyan.dao;

import com.cskaoyan.bean.Passenger;

import java.util.HashMap;
import java.util.List;

public interface PassengerMapper {


    int updateByPrimaryKey(Passenger record);

    //根据名字查旅客
    List<Passenger> findPassengerByName(String passenName);

    //查出所有的记录数
    int findAllPassengerCount();

    //查询所有的旅客
    List<Passenger> findAllPassenger();

    //查询部分
    List<Passenger> findPartPassenger(HashMap<String, Integer> map);

    //插入旅客
    int addPassenger(Passenger passenger);

    //通过属性id查对应的属性名
    String findPassengerAttributeByID(int id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    int deleteByPrimaryKey(Integer passengerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    int insert(Passenger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    int insertSelective(Passenger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    Passenger selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    int updateByPrimaryKeySelective(Passenger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */

}