package com.cskaoyan.dao;

import com.cskaoyan.bean.Recepobject;

public interface RecepobjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recepobject
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    int insert(Recepobject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recepobject
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    int insertSelective(Recepobject record);
}