package com.cskaoyan.dao;

import com.cskaoyan.bean.Roomsettype;

import java.util.ArrayList;

public interface RoomsettypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomsettype
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    int insert(Roomsettype record);

   // ArrayList<>

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomsettype
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    int insertSelective(Roomsettype record);
}