package com.cskaoyan.dao;

import com.cskaoyan.bean.Roomset;

public interface RoomsetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomset
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    int deleteByPrimaryKey(String roomsetid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomset
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    int insert(Roomset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomset
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    int insertSelective(Roomset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomset
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    Roomset selectByPrimaryKey(String roomsetid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomset
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    int updateByPrimaryKeySelective(Roomset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomset
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    int updateByPrimaryKey(Roomset record);
}