package com.cskaoyan.dao;

import com.cskaoyan.bean.Tour;

public interface TourMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tour
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    int deleteByPrimaryKey(Integer tourid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tour
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    int insert(Tour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tour
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    int insertSelective(Tour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tour
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    Tour selectByPrimaryKey(Integer tourid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tour
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    int updateByPrimaryKeySelective(Tour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tour
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    int updateByPrimaryKey(Tour record);
}