package com.cskaoyan.dao;

import com.cskaoyan.bean.Passenger;

public interface TourMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tour
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    int deleteByPrimaryKey(Integer tourid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tour
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    int insert(Passenger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tour
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    int insertSelective(Passenger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tour
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    Passenger selectByPrimaryKey(Integer tourid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tour
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    int updateByPrimaryKeySelective(Passenger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tour
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    int updateByPrimaryKey(Passenger record);
}