package com.cskaoyan.dao;

import com.cskaoyan.bean.PassengerDegree;

public interface TourdegreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tourdegree
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    int insert(PassengerDegree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tourdegree
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    int insertSelective(PassengerDegree record);
}