package com.cskaoyan.bean;

public class Changeroom {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column changeroom.id
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column changeroom.ordId
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private String ordid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column changeroom.oldroomset
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private String oldroomset;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column changeroom.newroomset
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private String newroomset;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column changeroom.affterPay
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private Float affterpay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column changeroom.del_flag
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column changeroom.id
     *
     * @return the value of changeroom.id
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column changeroom.id
     *
     * @param id the value for changeroom.id
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column changeroom.ordId
     *
     * @return the value of changeroom.ordId
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public String getOrdid() {
        return ordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column changeroom.ordId
     *
     * @param ordid the value for changeroom.ordId
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setOrdid(String ordid) {
        this.ordid = ordid == null ? null : ordid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column changeroom.oldroomset
     *
     * @return the value of changeroom.oldroomset
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public String getOldroomset() {
        return oldroomset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column changeroom.oldroomset
     *
     * @param oldroomset the value for changeroom.oldroomset
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setOldroomset(String oldroomset) {
        this.oldroomset = oldroomset == null ? null : oldroomset.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column changeroom.newroomset
     *
     * @return the value of changeroom.newroomset
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public String getNewroomset() {
        return newroomset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column changeroom.newroomset
     *
     * @param newroomset the value for changeroom.newroomset
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setNewroomset(String newroomset) {
        this.newroomset = newroomset == null ? null : newroomset.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column changeroom.affterPay
     *
     * @return the value of changeroom.affterPay
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public Float getAffterpay() {
        return affterpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column changeroom.affterPay
     *
     * @param affterpay the value for changeroom.affterPay
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setAffterpay(Float affterpay) {
        this.affterpay = affterpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column changeroom.del_flag
     *
     * @return the value of changeroom.del_flag
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column changeroom.del_flag
     *
     * @param delFlag the value for changeroom.del_flag
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}