package com.cskaoyan.bean;

public class Commodity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.commodityId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Integer commodityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.commodityName
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private String commodityname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.commodityTypeId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Integer commoditytypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.commodityMeasurementId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Integer commoditymeasurementid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.commodityPrice
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Float commodityprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.del_flag
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.commodityId
     *
     * @return the value of commodity.commodityId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public Integer getCommodityid() {
        return commodityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.commodityId
     *
     * @param commodityid the value for commodity.commodityId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setCommodityid(Integer commodityid) {
        this.commodityid = commodityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.commodityName
     *
     * @return the value of commodity.commodityName
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public String getCommodityname() {
        return commodityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.commodityName
     *
     * @param commodityname the value for commodity.commodityName
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setCommodityname(String commodityname) {
        this.commodityname = commodityname == null ? null : commodityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.commodityTypeId
     *
     * @return the value of commodity.commodityTypeId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public Integer getCommoditytypeid() {
        return commoditytypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.commodityTypeId
     *
     * @param commoditytypeid the value for commodity.commodityTypeId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setCommoditytypeid(Integer commoditytypeid) {
        this.commoditytypeid = commoditytypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.commodityMeasurementId
     *
     * @return the value of commodity.commodityMeasurementId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public Integer getCommoditymeasurementid() {
        return commoditymeasurementid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.commodityMeasurementId
     *
     * @param commoditymeasurementid the value for commodity.commodityMeasurementId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setCommoditymeasurementid(Integer commoditymeasurementid) {
        this.commoditymeasurementid = commoditymeasurementid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.commodityPrice
     *
     * @return the value of commodity.commodityPrice
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public Float getCommodityprice() {
        return commodityprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.commodityPrice
     *
     * @param commodityprice the value for commodity.commodityPrice
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setCommodityprice(Float commodityprice) {
        this.commodityprice = commodityprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.del_flag
     *
     * @return the value of commodity.del_flag
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.del_flag
     *
     * @param delFlag the value for commodity.del_flag
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}