package com.cskaoyan.bean;

/**
 * 商品类别类
 */
public class Commoditytype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commoditytype.commodityTypeId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Integer commoditytypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commoditytype.commodityTypeName
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private String commoditytypename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commoditytype.del_flag
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commoditytype.commodityTypeId
     *
     * @return the value of commoditytype.commodityTypeId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public Integer getCommoditytypeid() {
        return commoditytypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commoditytype.commodityTypeId
     *
     * @param commoditytypeid the value for commoditytype.commodityTypeId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setCommoditytypeid(Integer commoditytypeid) {
        this.commoditytypeid = commoditytypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commoditytype.commodityTypeName
     *
     * @return the value of commoditytype.commodityTypeName
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public String getCommoditytypename() {
        return commoditytypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commoditytype.commodityTypeName
     *
     * @param commoditytypename the value for commoditytype.commodityTypeName
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setCommoditytypename(String commoditytypename) {
        this.commoditytypename = commoditytypename == null ? null : commoditytypename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commoditytype.del_flag
     *
     * @return the value of commoditytype.del_flag
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commoditytype.del_flag
     *
     * @param delFlag the value for commoditytype.del_flag
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}