package com.cskaoyan.bean;

public class Commoditymeasurement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commoditymeasurement.commodityMeasurementId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Integer commoditymeasurementid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commoditymeasurement.commodityMeasurementName
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private String commoditymeasurementname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commoditymeasurement.del_flag
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commoditymeasurement.commodityMeasurementId
     *
     * @return the value of commoditymeasurement.commodityMeasurementId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public Integer getCommoditymeasurementid() {
        return commoditymeasurementid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commoditymeasurement.commodityMeasurementId
     *
     * @param commoditymeasurementid the value for commoditymeasurement.commodityMeasurementId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setCommoditymeasurementid(Integer commoditymeasurementid) {
        this.commoditymeasurementid = commoditymeasurementid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commoditymeasurement.commodityMeasurementName
     *
     * @return the value of commoditymeasurement.commodityMeasurementName
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public String getCommoditymeasurementname() {
        return commoditymeasurementname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commoditymeasurement.commodityMeasurementName
     *
     * @param commoditymeasurementname the value for commoditymeasurement.commodityMeasurementName
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setCommoditymeasurementname(String commoditymeasurementname) {
        this.commoditymeasurementname = commoditymeasurementname == null ? null : commoditymeasurementname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commoditymeasurement.del_flag
     *
     * @return the value of commoditymeasurement.del_flag
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commoditymeasurement.del_flag
     *
     * @param delFlag the value for commoditymeasurement.del_flag
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}