package com.cskaoyan.bean;

import java.util.Date;

public class Financialstatistics {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financialstatistics.financialstatisticsId
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private Integer financialstatisticsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financialstatistics.roomNumber
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private Integer roomnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financialstatistics.predetermineReceiveTargeTypeName
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private String predeterminereceivetargetypename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financialstatistics.receiveTeamName
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private String receiveteamname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financialstatistics.passengerName
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private String passengername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financialstatistics.changingRoomNumber
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private String changingroomnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financialstatistics.changRoomTime
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private Date changroomtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financialstatistics.registerTime
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private Date registertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financialstatistics.payTime
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private Date paytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financialstatistics.sumConst
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private Float sumconst;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financialstatistics.stayregisterdetailsId
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private Integer stayregisterdetailsid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financialstatistics.financialstatisticsId
     *
     * @return the value of financialstatistics.financialstatisticsId
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public Integer getFinancialstatisticsid() {
        return financialstatisticsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financialstatistics.financialstatisticsId
     *
     * @param financialstatisticsid the value for financialstatistics.financialstatisticsId
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setFinancialstatisticsid(Integer financialstatisticsid) {
        this.financialstatisticsid = financialstatisticsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financialstatistics.roomNumber
     *
     * @return the value of financialstatistics.roomNumber
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public Integer getRoomnumber() {
        return roomnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financialstatistics.roomNumber
     *
     * @param roomnumber the value for financialstatistics.roomNumber
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setRoomnumber(Integer roomnumber) {
        this.roomnumber = roomnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financialstatistics.predetermineReceiveTargeTypeName
     *
     * @return the value of financialstatistics.predetermineReceiveTargeTypeName
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public String getPredeterminereceivetargetypename() {
        return predeterminereceivetargetypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financialstatistics.predetermineReceiveTargeTypeName
     *
     * @param predeterminereceivetargetypename the value for financialstatistics.predetermineReceiveTargeTypeName
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setPredeterminereceivetargetypename(String predeterminereceivetargetypename) {
        this.predeterminereceivetargetypename = predeterminereceivetargetypename == null ? null : predeterminereceivetargetypename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financialstatistics.receiveTeamName
     *
     * @return the value of financialstatistics.receiveTeamName
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public String getReceiveteamname() {
        return receiveteamname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financialstatistics.receiveTeamName
     *
     * @param receiveteamname the value for financialstatistics.receiveTeamName
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setReceiveteamname(String receiveteamname) {
        this.receiveteamname = receiveteamname == null ? null : receiveteamname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financialstatistics.passengerName
     *
     * @return the value of financialstatistics.passengerName
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public String getPassengername() {
        return passengername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financialstatistics.passengerName
     *
     * @param passengername the value for financialstatistics.passengerName
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setPassengername(String passengername) {
        this.passengername = passengername == null ? null : passengername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financialstatistics.changingRoomNumber
     *
     * @return the value of financialstatistics.changingRoomNumber
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public String getChangingroomnumber() {
        return changingroomnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financialstatistics.changingRoomNumber
     *
     * @param changingroomnumber the value for financialstatistics.changingRoomNumber
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setChangingroomnumber(String changingroomnumber) {
        this.changingroomnumber = changingroomnumber == null ? null : changingroomnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financialstatistics.changRoomTime
     *
     * @return the value of financialstatistics.changRoomTime
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public Date getChangroomtime() {
        return changroomtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financialstatistics.changRoomTime
     *
     * @param changroomtime the value for financialstatistics.changRoomTime
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setChangroomtime(Date changroomtime) {
        this.changroomtime = changroomtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financialstatistics.registerTime
     *
     * @return the value of financialstatistics.registerTime
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public Date getRegistertime() {
        return registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financialstatistics.registerTime
     *
     * @param registertime the value for financialstatistics.registerTime
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setRegistertime(Date registertime) {
        this.registertime = registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financialstatistics.payTime
     *
     * @return the value of financialstatistics.payTime
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public Date getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financialstatistics.payTime
     *
     * @param paytime the value for financialstatistics.payTime
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setPaytime(Date paytime) {
        this.paytime = paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financialstatistics.sumConst
     *
     * @return the value of financialstatistics.sumConst
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public Float getSumconst() {
        return sumconst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financialstatistics.sumConst
     *
     * @param sumconst the value for financialstatistics.sumConst
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setSumconst(Float sumconst) {
        this.sumconst = sumconst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financialstatistics.stayregisterdetailsId
     *
     * @return the value of financialstatistics.stayregisterdetailsId
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public Integer getStayregisterdetailsid() {
        return stayregisterdetailsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financialstatistics.stayregisterdetailsId
     *
     * @param stayregisterdetailsid the value for financialstatistics.stayregisterdetailsId
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setStayregisterdetailsid(Integer stayregisterdetailsid) {
        this.stayregisterdetailsid = stayregisterdetailsid;
    }
}