package com.cskaoyan.bean;

public class Ordcheckinpassenger {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordcheckinpassenger.id
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordcheckinpassenger.ordId
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    private String ordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordcheckinpassenger.checkinPassengerId
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    private Integer checkinPassengerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordcheckinpassenger.delFlag
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordcheckinpassenger.id
     *
     * @return the value of ordcheckinpassenger.id
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordcheckinpassenger.id
     *
     * @param id the value for ordcheckinpassenger.id
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordcheckinpassenger.ordId
     *
     * @return the value of ordcheckinpassenger.ordId
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public String getOrdId() {
        return ordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordcheckinpassenger.ordId
     *
     * @param ordId the value for ordcheckinpassenger.ordId
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public void setOrdId(String ordId) {
        this.ordId = ordId == null ? null : ordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordcheckinpassenger.checkinPassengerId
     *
     * @return the value of ordcheckinpassenger.checkinPassengerId
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public Integer getCheckinPassengerId() {
        return checkinPassengerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordcheckinpassenger.checkinPassengerId
     *
     * @param checkinPassengerId the value for ordcheckinpassenger.checkinPassengerId
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public void setCheckinPassengerId(Integer checkinPassengerId) {
        this.checkinPassengerId = checkinPassengerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordcheckinpassenger.delFlag
     *
     * @return the value of ordcheckinpassenger.delFlag
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordcheckinpassenger.delFlag
     *
     * @param delFlag the value for ordcheckinpassenger.delFlag
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}