package com.cskaoyan.bean;

public class Ordextconsum {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordextconsum.id
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordextconsum.ord_id
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    private String ord_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordextconsum.commodity_id
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    private Integer commodity_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordextconsum.num
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordextconsum.del_flag
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    private Integer del_flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordextconsum.id
     *
     * @return the value of ordextconsum.id
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordextconsum.id
     *
     * @param id the value for ordextconsum.id
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordextconsum.ord_id
     *
     * @return the value of ordextconsum.ord_id
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public String getOrd_id() {
        return ord_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordextconsum.ord_id
     *
     * @param ord_id the value for ordextconsum.ord_id
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public void setOrd_id(String ord_id) {
        this.ord_id = ord_id == null ? null : ord_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordextconsum.commodity_id
     *
     * @return the value of ordextconsum.commodity_id
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public Integer getCommodity_id() {
        return commodity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordextconsum.commodity_id
     *
     * @param commodity_id the value for ordextconsum.commodity_id
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public void setCommodity_id(Integer commodity_id) {
        this.commodity_id = commodity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordextconsum.num
     *
     * @return the value of ordextconsum.num
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordextconsum.num
     *
     * @param num the value for ordextconsum.num
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordextconsum.del_flag
     *
     * @return the value of ordextconsum.del_flag
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public Integer getDel_flag() {
        return del_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordextconsum.del_flag
     *
     * @param del_flag the value for ordextconsum.del_flag
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public void setDel_flag(Integer del_flag) {
        this.del_flag = del_flag;
    }
}