package com.cskaoyan.bean;

public class Orderpayment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderpayment.far_id
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    private Integer far_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderpayment.attributeDetailsName
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    private String attributeDetailsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderpayment.delFlag
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderpayment.far_id
     *
     * @return the value of orderpayment.far_id
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public Integer getFar_id() {
        return far_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderpayment.far_id
     *
     * @param far_id the value for orderpayment.far_id
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public void setFar_id(Integer far_id) {
        this.far_id = far_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderpayment.attributeDetailsName
     *
     * @return the value of orderpayment.attributeDetailsName
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public String getAttributeDetailsName() {
        return attributeDetailsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderpayment.attributeDetailsName
     *
     * @param attributeDetailsName the value for orderpayment.attributeDetailsName
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public void setAttributeDetailsName(String attributeDetailsName) {
        this.attributeDetailsName = attributeDetailsName == null ? null : attributeDetailsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderpayment.delFlag
     *
     * @return the value of orderpayment.delFlag
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderpayment.delFlag
     *
     * @param delFlag the value for orderpayment.delFlag
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}