package com.cskaoyan.bean;

public class Ordextconsum {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordextconsum.id
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordextconsum.ordId
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private String ordid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordextconsum.commodityId
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private Integer commodityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordextconsum.num
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordextconsum.del_flag
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordextconsum.id
     *
     * @return the value of ordextconsum.id
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordextconsum.id
     *
     * @param id the value for ordextconsum.id
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordextconsum.ordId
     *
     * @return the value of ordextconsum.ordId
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public String getOrdid() {
        return ordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordextconsum.ordId
     *
     * @param ordid the value for ordextconsum.ordId
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setOrdid(String ordid) {
        this.ordid = ordid == null ? null : ordid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordextconsum.commodityId
     *
     * @return the value of ordextconsum.commodityId
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public Integer getCommodityid() {
        return commodityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordextconsum.commodityId
     *
     * @param commodityid the value for ordextconsum.commodityId
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setCommodityid(Integer commodityid) {
        this.commodityid = commodityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordextconsum.num
     *
     * @return the value of ordextconsum.num
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordextconsum.num
     *
     * @param num the value for ordextconsum.num
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordextconsum.del_flag
     *
     * @return the value of ordextconsum.del_flag
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordextconsum.del_flag
     *
     * @param delFlag the value for ordextconsum.del_flag
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}