package com.cskaoyan.bean;

import java.util.ArrayList;
import java.util.Date;

public class Ordermain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordermain.ordID
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    private String ordID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordermain.passengerOrReceiveID
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    private Integer passengerOrReceiveID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordermain.receiveTargetID
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    private Integer receiveTargetID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordermain.status
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordermain.rentOutTypeName
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    private Integer rentOutTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordermain.stayNumber
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    private Integer stayNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordermain.deposit
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    private Float deposit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordermain.orderPaymentId
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    private Integer orderPaymentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordermain.arrivalTime
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    private Date arrivalTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordermain.roomNumber
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    private String roomNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordermain.orderTime
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    private Date orderTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordermain.registerTime
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    private Date registerTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordermain.payTime
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    private Date payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordermain.sumConst
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    private Float sumConst;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordermain.delFlag
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordermain.ordID
     *
     * @return the value of ordermain.ordID
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public String getOrdID() {
        return ordID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordermain.ordID
     *
     * @param ordID the value for ordermain.ordID
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public void setOrdID(String ordID) {
        this.ordID = ordID == null ? null : ordID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordermain.passengerOrReceiveID
     *
     * @return the value of ordermain.passengerOrReceiveID
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public Integer getPassengerOrReceiveID() {
        return passengerOrReceiveID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordermain.passengerOrReceiveID
     *
     * @param passengerOrReceiveID the value for ordermain.passengerOrReceiveID
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public void setPassengerOrReceiveID(Integer passengerOrReceiveID) {
        this.passengerOrReceiveID = passengerOrReceiveID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordermain.receiveTargetID
     *
     * @return the value of ordermain.receiveTargetID
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public Integer getReceiveTargetID() {
        return receiveTargetID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordermain.receiveTargetID
     *
     * @param receiveTargetID the value for ordermain.receiveTargetID
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public void setReceiveTargetID(Integer receiveTargetID) {
        this.receiveTargetID = receiveTargetID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordermain.status
     *
     * @return the value of ordermain.status
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordermain.status
     *
     * @param status the value for ordermain.status
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordermain.rentOutTypeName
     *
     * @return the value of ordermain.rentOutTypeName
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public Integer getRentOutTypeName() {
        return rentOutTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordermain.rentOutTypeName
     *
     * @param rentOutTypeName the value for ordermain.rentOutTypeName
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public void setRentOutTypeName(Integer rentOutTypeName) {
        this.rentOutTypeName = rentOutTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordermain.stayNumber
     *
     * @return the value of ordermain.stayNumber
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public Integer getStayNumber() {
        return stayNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordermain.stayNumber
     *
     * @param stayNumber the value for ordermain.stayNumber
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public void setStayNumber(Integer stayNumber) {
        this.stayNumber = stayNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordermain.deposit
     *
     * @return the value of ordermain.deposit
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public Float getDeposit() {
        return deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordermain.deposit
     *
     * @param deposit the value for ordermain.deposit
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public void setDeposit(Float deposit) {
        this.deposit = deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordermain.orderPaymentId
     *
     * @return the value of ordermain.orderPaymentId
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public Integer getOrderPaymentId() {
        return orderPaymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordermain.orderPaymentId
     *
     * @param orderPaymentId the value for ordermain.orderPaymentId
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public void setOrderPaymentId(Integer orderPaymentId) {
        this.orderPaymentId = orderPaymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordermain.arrivalTime
     *
     * @return the value of ordermain.arrivalTime
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public Date getArrivalTime() {
        return arrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordermain.arrivalTime
     *
     * @param arrivalTime the value for ordermain.arrivalTime
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public void setArrivalTime(Date arrivalTime) {
        this.arrivalTime = arrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordermain.roomNumber
     *
     * @return the value of ordermain.roomNumber
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public String getRoomNumber() {
        return roomNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordermain.roomNumber
     *
     * @param roomNumber the value for ordermain.roomNumber
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public void setRoomNumber(String roomNumber) {
        this.roomNumber = roomNumber == null ? null : roomNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordermain.orderTime
     *
     * @return the value of ordermain.orderTime
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordermain.orderTime
     *
     * @param orderTime the value for ordermain.orderTime
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordermain.registerTime
     *
     * @return the value of ordermain.registerTime
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordermain.registerTime
     *
     * @param registerTime the value for ordermain.registerTime
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordermain.payTime
     *
     * @return the value of ordermain.payTime
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordermain.payTime
     *
     * @param payTime the value for ordermain.payTime
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordermain.sumConst
     *
     * @return the value of ordermain.sumConst
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public Float getSumConst() {
        return sumConst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordermain.sumConst
     *
     * @param sumConst the value for ordermain.sumConst
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public void setSumConst(Float sumConst) {
        this.sumConst = sumConst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordermain.delFlag
     *
     * @return the value of ordermain.delFlag
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordermain.delFlag
     *
     * @param delFlag the value for ordermain.delFlag
     *
     * @mbg.generated Wed Apr 11 22:30:33 CST 2018
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }




    /**
     * 如果是个人预定包含预定人信息
     */
    private Passenger passenger;

    /**
     * 如果是团队包含团队信息
     */
    private Recepobject recepobject;

    /**
     * 支付方式成员函数，一对一
     */
    private Orderpayment orderpayment;
    /**
     * 预定房间具体信息，一对一
     */

    private Roomset roomset;

    /**
     * 换房次数,不存数据库,每次重新查询，后续若影响性能可以考虑加库
     */

    private int changNum;

    /**
     * 换房信息，有可能是一个list
     */
    private ArrayList<Changeroom> changerooms;


    public Passenger getPassenger() {
        return passenger;
    }

    public void setPassenger(Passenger passenger) {
        this.passenger = passenger;
    }

    public Recepobject getRecepobject() {
        return recepobject;
    }

    public void setRecepobject(Recepobject recepobject) {
        this.recepobject = recepobject;
    }

    public Orderpayment getOrderpayment() {
        return orderpayment;
    }

    public void setOrderpayment(Orderpayment orderpayment) {
        this.orderpayment = orderpayment;
    }

    public Roomset getRoomset() {
        return roomset;
    }

    public void setRoomset(Roomset roomset) {
        this.roomset = roomset;
    }

    public int getChangNum() {
        return changNum;
    }

    public void setChangNum(int changNum) {
        this.changNum = changNum;
    }

    public ArrayList<Changeroom> getChangerooms() {
        return changerooms;
    }

    public void setChangerooms(ArrayList<Changeroom> changerooms) {
        this.changerooms = changerooms;
    }

}