package com.cskaoyan.bean;

import java.util.ArrayList;
import java.util.Date;

public class Ordermain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordermain.ordId
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    private String ordid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordermain.ordPassengerId
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    private Integer ordpassengerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordermain.sign
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    private Integer sign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordermain.status
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordermain.ordType
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    private Integer ordtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordermain.ordDayNum
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    private Integer orddaynum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordermain.deposit
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    private Float deposit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordermain.orderPaymentId
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    private Integer orderpaymentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordermain.arrivalTime
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    private Date arrivaltime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordermain.roomsetId
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    private String roomsetid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordermain.OrderTime
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    private Date ordertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordermain.checkInTime
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    private Date checkintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordermain.checkOutTime
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    private Date checkouttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordermain.checkOutMoney
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    private Float checkoutmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordermain.del_flag
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordermain.ordId
     *
     * @return the value of ordermain.ordId
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    public String getOrdid() {
        return ordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordermain.ordId
     *
     * @param ordid the value for ordermain.ordId
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    public void setOrdid(String ordid) {
        this.ordid = ordid == null ? null : ordid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordermain.ordPassengerId
     *
     * @return the value of ordermain.ordPassengerId
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    public Integer getOrdpassengerid() {
        return ordpassengerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordermain.ordPassengerId
     *
     * @param ordpassengerid the value for ordermain.ordPassengerId
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    public void setOrdpassengerid(Integer ordpassengerid) {
        this.ordpassengerid = ordpassengerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordermain.sign
     *
     * @return the value of ordermain.sign
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    public Integer getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordermain.sign
     *
     * @param sign the value for ordermain.sign
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    public void setSign(Integer sign) {
        this.sign = sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordermain.status
     *
     * @return the value of ordermain.status
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordermain.status
     *
     * @param status the value for ordermain.status
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordermain.ordType
     *
     * @return the value of ordermain.ordType
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    public Integer getOrdtype() {
        return ordtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordermain.ordType
     *
     * @param ordtype the value for ordermain.ordType
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    public void setOrdtype(Integer ordtype) {
        this.ordtype = ordtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordermain.ordDayNum
     *
     * @return the value of ordermain.ordDayNum
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    public Integer getOrddaynum() {
        return orddaynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordermain.ordDayNum
     *
     * @param orddaynum the value for ordermain.ordDayNum
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    public void setOrddaynum(Integer orddaynum) {
        this.orddaynum = orddaynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordermain.deposit
     *
     * @return the value of ordermain.deposit
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    public Float getDeposit() {
        return deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordermain.deposit
     *
     * @param deposit the value for ordermain.deposit
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    public void setDeposit(Float deposit) {
        this.deposit = deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordermain.orderPaymentId
     *
     * @return the value of ordermain.orderPaymentId
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    public Integer getOrderpaymentid() {
        return orderpaymentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordermain.orderPaymentId
     *
     * @param orderpaymentid the value for ordermain.orderPaymentId
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    public void setOrderpaymentid(Integer orderpaymentid) {
        this.orderpaymentid = orderpaymentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordermain.arrivalTime
     *
     * @return the value of ordermain.arrivalTime
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    public Date getArrivaltime() {
        return arrivaltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordermain.arrivalTime
     *
     * @param arrivaltime the value for ordermain.arrivalTime
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    public void setArrivaltime(Date arrivaltime) {
        this.arrivaltime = arrivaltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordermain.roomsetId
     *
     * @return the value of ordermain.roomsetId
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    public String getRoomsetid() {
        return roomsetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordermain.roomsetId
     *
     * @param roomsetid the value for ordermain.roomsetId
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    public void setRoomsetid(String roomsetid) {
        this.roomsetid = roomsetid == null ? null : roomsetid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordermain.OrderTime
     *
     * @return the value of ordermain.OrderTime
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    public Date getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordermain.OrderTime
     *
     * @param ordertime the value for ordermain.OrderTime
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    public void setOrdertime(Date ordertime) {
        this.ordertime = ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordermain.checkInTime
     *
     * @return the value of ordermain.checkInTime
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    public Date getCheckintime() {
        return checkintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordermain.checkInTime
     *
     * @param checkintime the value for ordermain.checkInTime
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    public void setCheckintime(Date checkintime) {
        this.checkintime = checkintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordermain.checkOutTime
     *
     * @return the value of ordermain.checkOutTime
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    public Date getCheckouttime() {
        return checkouttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordermain.checkOutTime
     *
     * @param checkouttime the value for ordermain.checkOutTime
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    public void setCheckouttime(Date checkouttime) {
        this.checkouttime = checkouttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordermain.checkOutMoney
     *
     * @return the value of ordermain.checkOutMoney
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    public Float getCheckoutmoney() {
        return checkoutmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordermain.checkOutMoney
     *
     * @param checkoutmoney the value for ordermain.checkOutMoney
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    public void setCheckoutmoney(Float checkoutmoney) {
        this.checkoutmoney = checkoutmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordermain.del_flag
     *
     * @return the value of ordermain.del_flag
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordermain.del_flag
     *
     * @param delFlag the value for ordermain.del_flag
     *
     * @mbg.generated Wed Apr 11 18:20:53 CST 2018
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }



    /**
     * 如果是个人预定包含预定人信息
     */
    private Passenger passenger;

    /**
     * 如果是团队包含团队信息
     */
    private Recepobject recepobject;

    /**
     * 支付方式成员函数，一对一
     */
    private Orderpayment orderpayment;
    /**
     * 预定房间具体信息，一对一
     */

    private Roomset roomset;

    /**
     * 换房次数,不存数据库,每次重新查询，后续若影响性能可以考虑加库
     */

    private int changNum;

    /**
     * 换房信息，有可能是一个list
     */
    private ArrayList<Changeroom> changerooms;


    public Passenger getPassenger() {
        return passenger;
    }

    public void setPassenger(Passenger passenger) {
        this.passenger = passenger;
    }

    public Recepobject getRecepobject() {
        return recepobject;
    }

    public void setRecepobject(Recepobject recepobject) {
        this.recepobject = recepobject;
    }

    public Orderpayment getOrderpayment() {
        return orderpayment;
    }

    public void setOrderpayment(Orderpayment orderpayment) {
        this.orderpayment = orderpayment;
    }

    public Roomset getRoomset() {
        return roomset;
    }

    public void setRoomset(Roomset roomset) {
        this.roomset = roomset;
    }

    public int getChangNum() {
        return changNum;
    }

    public void setChangNum(int changNum) {
        this.changNum = changNum;
    }

    public ArrayList<Changeroom> getChangerooms() {
        return changerooms;
    }

    public void setChangerooms(ArrayList<Changeroom> changerooms) {
        this.changerooms = changerooms;
    }
}