package com.cskaoyan.bean;

import java.util.Date;

public class Passenger {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.passengerId
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private Integer passengerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.passengerName
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private String passengername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.genderName
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private String gendername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.birthDate
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private Date birthdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.nationName
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private String nationname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.tourIdentifyInstisution
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private String touridentifyinstisution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.tourIdentifyValidDate
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private Date touridentifyvaliddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.tourRank
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private String tourrank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.tourIdentifyType
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private String touridentifytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.CardId
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private String cardid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.tourCareer
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private String tourcareer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.tourDegreeId
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private String tourdegreeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.tourAddress
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private String touraddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.tourForPropose
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private String tourforpropose;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.tourFromPlace
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private String tourfromplace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.tourToPlace
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private String tourtoplace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.tourContacePhone
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private Integer tourcontacephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.tourComment
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private String tourcomment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.del_flag
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.passengerId
     *
     * @return the value of passenger.passengerId
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public Integer getPassengerid() {
        return passengerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.passengerId
     *
     * @param passengerid the value for passenger.passengerId
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setPassengerid(Integer passengerid) {
        this.passengerid = passengerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.passengerName
     *
     * @return the value of passenger.passengerName
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public String getPassengername() {
        return passengername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.passengerName
     *
     * @param passengername the value for passenger.passengerName
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setPassengername(String passengername) {
        this.passengername = passengername == null ? null : passengername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.genderName
     *
     * @return the value of passenger.genderName
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public String getGendername() {
        return gendername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.genderName
     *
     * @param gendername the value for passenger.genderName
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setGendername(String gendername) {
        this.gendername = gendername == null ? null : gendername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.birthDate
     *
     * @return the value of passenger.birthDate
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public Date getBirthdate() {
        return birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.birthDate
     *
     * @param birthdate the value for passenger.birthDate
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.nationName
     *
     * @return the value of passenger.nationName
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public String getNationname() {
        return nationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.nationName
     *
     * @param nationname the value for passenger.nationName
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setNationname(String nationname) {
        this.nationname = nationname == null ? null : nationname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.tourIdentifyInstisution
     *
     * @return the value of passenger.tourIdentifyInstisution
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public String getTouridentifyinstisution() {
        return touridentifyinstisution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.tourIdentifyInstisution
     *
     * @param touridentifyinstisution the value for passenger.tourIdentifyInstisution
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setTouridentifyinstisution(String touridentifyinstisution) {
        this.touridentifyinstisution = touridentifyinstisution == null ? null : touridentifyinstisution.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.tourIdentifyValidDate
     *
     * @return the value of passenger.tourIdentifyValidDate
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public Date getTouridentifyvaliddate() {
        return touridentifyvaliddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.tourIdentifyValidDate
     *
     * @param touridentifyvaliddate the value for passenger.tourIdentifyValidDate
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setTouridentifyvaliddate(Date touridentifyvaliddate) {
        this.touridentifyvaliddate = touridentifyvaliddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.tourRank
     *
     * @return the value of passenger.tourRank
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public String getTourrank() {
        return tourrank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.tourRank
     *
     * @param tourrank the value for passenger.tourRank
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setTourrank(String tourrank) {
        this.tourrank = tourrank == null ? null : tourrank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.tourIdentifyType
     *
     * @return the value of passenger.tourIdentifyType
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public String getTouridentifytype() {
        return touridentifytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.tourIdentifyType
     *
     * @param touridentifytype the value for passenger.tourIdentifyType
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setTouridentifytype(String touridentifytype) {
        this.touridentifytype = touridentifytype == null ? null : touridentifytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.CardId
     *
     * @return the value of passenger.CardId
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public String getCardid() {
        return cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.CardId
     *
     * @param cardid the value for passenger.CardId
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setCardid(String cardid) {
        this.cardid = cardid == null ? null : cardid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.tourCareer
     *
     * @return the value of passenger.tourCareer
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public String getTourcareer() {
        return tourcareer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.tourCareer
     *
     * @param tourcareer the value for passenger.tourCareer
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setTourcareer(String tourcareer) {
        this.tourcareer = tourcareer == null ? null : tourcareer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.tourDegreeId
     *
     * @return the value of passenger.tourDegreeId
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public String getTourdegreeid() {
        return tourdegreeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.tourDegreeId
     *
     * @param tourdegreeid the value for passenger.tourDegreeId
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setTourdegreeid(String tourdegreeid) {
        this.tourdegreeid = tourdegreeid == null ? null : tourdegreeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.tourAddress
     *
     * @return the value of passenger.tourAddress
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public String getTouraddress() {
        return touraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.tourAddress
     *
     * @param touraddress the value for passenger.tourAddress
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setTouraddress(String touraddress) {
        this.touraddress = touraddress == null ? null : touraddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.tourForPropose
     *
     * @return the value of passenger.tourForPropose
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public String getTourforpropose() {
        return tourforpropose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.tourForPropose
     *
     * @param tourforpropose the value for passenger.tourForPropose
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setTourforpropose(String tourforpropose) {
        this.tourforpropose = tourforpropose == null ? null : tourforpropose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.tourFromPlace
     *
     * @return the value of passenger.tourFromPlace
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public String getTourfromplace() {
        return tourfromplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.tourFromPlace
     *
     * @param tourfromplace the value for passenger.tourFromPlace
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setTourfromplace(String tourfromplace) {
        this.tourfromplace = tourfromplace == null ? null : tourfromplace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.tourToPlace
     *
     * @return the value of passenger.tourToPlace
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public String getTourtoplace() {
        return tourtoplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.tourToPlace
     *
     * @param tourtoplace the value for passenger.tourToPlace
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setTourtoplace(String tourtoplace) {
        this.tourtoplace = tourtoplace == null ? null : tourtoplace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.tourContacePhone
     *
     * @return the value of passenger.tourContacePhone
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public Integer getTourcontacephone() {
        return tourcontacephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.tourContacePhone
     *
     * @param tourcontacephone the value for passenger.tourContacePhone
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setTourcontacephone(Integer tourcontacephone) {
        this.tourcontacephone = tourcontacephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.tourComment
     *
     * @return the value of passenger.tourComment
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public String getTourcomment() {
        return tourcomment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.tourComment
     *
     * @param tourcomment the value for passenger.tourComment
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setTourcomment(String tourcomment) {
        this.tourcomment = tourcomment == null ? null : tourcomment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.del_flag
     *
     * @return the value of passenger.del_flag
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.del_flag
     *
     * @param delFlag the value for passenger.del_flag
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}