package com.cskaoyan.bean;

public class PassengerDegree {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tourdegree.tourDegreeId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Integer tourdegreeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tourdegree.tourDegreeName
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private String tourdegreename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tourdegree.tourDegreeId
     *
     * @return the value of tourdegree.tourDegreeId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public Integer getTourdegreeid() {
        return tourdegreeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tourdegree.tourDegreeId
     *
     * @param tourdegreeid the value for tourdegree.tourDegreeId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setTourdegreeid(Integer tourdegreeid) {
        this.tourdegreeid = tourdegreeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tourdegree.tourDegreeName
     *
     * @return the value of tourdegree.tourDegreeName
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public String getTourdegreename() {
        return tourdegreename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tourdegree.tourDegreeName
     *
     * @param tourdegreename the value for tourdegree.tourDegreeName
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setTourdegreename(String tourdegreename) {
        this.tourdegreename = tourdegreename == null ? null : tourdegreename.trim();
    }
}