package com.cskaoyan.bean;

public class Passengerdegree {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tourdegree.tourDegreeId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Integer far_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tourdegree.tourDegreeName
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private String passengerDegreeName;

    public Integer getFar_id() {
        return far_id;
    }

    public void setFar_id(Integer far_id) {
        this.far_id = far_id;
    }

    public String getPassengerDegreeName() {
        return passengerDegreeName;
    }

    public void setPassengerDegreeName(String passengerDegreeName) {
        this.passengerDegreeName = passengerDegreeName;
    }
}