package com.cskaoyan.bean;

import java.util.Date;

public class Passenger {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.id
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.name
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.genderID
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    private String genderID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.genderName
     *
     * @mbg.generated Thu Apr 12 22:29:50 CST 2018
     */
    private String genderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.birthDate
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    private Date birthDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.nationID
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    private String nationID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.nationName
     *
     * @mbg.generated Thu Apr 12 22:29:50 CST 2018
     */
    private String nationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.licenceIssuingAuthorty
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    private String licenceIssuingAuthorty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.papersValidity
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    private Date papersValidity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.profession
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    private String profession;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.educationDegreeID
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    private String educationDegreeID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.educationDegreeName
     *
     * @mbg.generated Thu Apr 12 22:29:50 CST 2018
     */
    private String educationDegreeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.passengerLevelID
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    private String passengerLevelID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.papersID
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    private String papersID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.papersName
     *
     * @mbg.generated Thu Apr 12 22:29:50 CST 2018
     */
    private String papersName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.papersNumber
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    private String papersNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.unitsOrAddress
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    private String unitsOrAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.thingReasonID
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    private String thingReasonID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.thingReasonName
     *
     * @mbg.generated Thu Apr 12 22:29:50 CST 2018
     */
    private String thingReasonName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.whereAreFrom
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    private String whereAreFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.whereToGo
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    private String whereToGo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.contactPhoneNumber
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    private String contactPhoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.remarks
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.del_flag
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    private Integer del_flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.id
     *
     * @return the value of passenger.id
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.id
     *
     * @param id the value for passenger.id
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.name
     *
     * @return the value of passenger.name
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.name
     *
     * @param name the value for passenger.name
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.genderID
     *
     * @return the value of passenger.genderID
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public String getGenderID() {
        return genderID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.genderID
     *
     * @param genderID the value for passenger.genderID
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public void setGenderID(String genderID) {
        this.genderID = genderID == null ? null : genderID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.genderName
     *
     * @return the value of passenger.genderName
     *
     * @mbg.generated Thu Apr 12 22:29:50 CST 2018
     */
    public String getGenderName() {
        return genderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.genderName
     *
     * @param genderName the value for passenger.genderName
     *
     * @mbg.generated Thu Apr 12 22:29:50 CST 2018
     */
    public void setGenderName(String genderName) {
        this.genderName = genderName == null ? null : genderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.birthDate
     *
     * @return the value of passenger.birthDate
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public Date getBirthDate() {
        return birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.birthDate
     *
     * @param birthDate the value for passenger.birthDate
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.nationID
     *
     * @return the value of passenger.nationID
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public String getNationID() {
        return nationID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.nationID
     *
     * @param nationID the value for passenger.nationID
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public void setNationID(String nationID) {
        this.nationID = nationID == null ? null : nationID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.nationName
     *
     * @return the value of passenger.nationName
     *
     * @mbg.generated Thu Apr 12 22:29:50 CST 2018
     */
    public String getNationName() {
        return nationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.nationName
     *
     * @param nationName the value for passenger.nationName
     *
     * @mbg.generated Thu Apr 12 22:29:50 CST 2018
     */
    public void setNationName(String nationName) {
        this.nationName = nationName == null ? null : nationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.licenceIssuingAuthorty
     *
     * @return the value of passenger.licenceIssuingAuthorty
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public String getLicenceIssuingAuthorty() {
        return licenceIssuingAuthorty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.licenceIssuingAuthorty
     *
     * @param licenceIssuingAuthorty the value for passenger.licenceIssuingAuthorty
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public void setLicenceIssuingAuthorty(String licenceIssuingAuthorty) {
        this.licenceIssuingAuthorty = licenceIssuingAuthorty == null ? null : licenceIssuingAuthorty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.papersValidity
     *
     * @return the value of passenger.papersValidity
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public Date getPapersValidity() {
        return papersValidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.papersValidity
     *
     * @param papersValidity the value for passenger.papersValidity
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public void setPapersValidity(Date papersValidity) {
        this.papersValidity = papersValidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.profession
     *
     * @return the value of passenger.profession
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public String getProfession() {
        return profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.profession
     *
     * @param profession the value for passenger.profession
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public void setProfession(String profession) {
        this.profession = profession == null ? null : profession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.educationDegreeID
     *
     * @return the value of passenger.educationDegreeID
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public String getEducationDegreeID() {
        return educationDegreeID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.educationDegreeID
     *
     * @param educationDegreeID the value for passenger.educationDegreeID
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public void setEducationDegreeID(String educationDegreeID) {
        this.educationDegreeID = educationDegreeID == null ? null : educationDegreeID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.educationDegreeName
     *
     * @return the value of passenger.educationDegreeName
     *
     * @mbg.generated Thu Apr 12 22:29:50 CST 2018
     */
    public String getEducationDegreeName() {
        return educationDegreeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.educationDegreeName
     *
     * @param educationDegreeName the value for passenger.educationDegreeName
     *
     * @mbg.generated Thu Apr 12 22:29:50 CST 2018
     */
    public void setEducationDegreeName(String educationDegreeName) {
        this.educationDegreeName = educationDegreeName == null ? null : educationDegreeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.passengerLevelID
     *
     * @return the value of passenger.passengerLevelID
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public String getPassengerLevelID() {
        return passengerLevelID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.passengerLevelID
     *
     * @param passengerLevelID the value for passenger.passengerLevelID
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public void setPassengerLevelID(String passengerLevelID) {
        this.passengerLevelID = passengerLevelID == null ? null : passengerLevelID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.papersID
     *
     * @return the value of passenger.papersID
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public String getPapersID() {
        return papersID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.papersID
     *
     * @param papersID the value for passenger.papersID
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public void setPapersID(String papersID) {
        this.papersID = papersID == null ? null : papersID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.papersName
     *
     * @return the value of passenger.papersName
     *
     * @mbg.generated Thu Apr 12 22:29:50 CST 2018
     */
    public String getPapersName() {
        return papersName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.papersName
     *
     * @param papersName the value for passenger.papersName
     *
     * @mbg.generated Thu Apr 12 22:29:50 CST 2018
     */
    public void setPapersName(String papersName) {
        this.papersName = papersName == null ? null : papersName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.papersNumber
     *
     * @return the value of passenger.papersNumber
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public String getPapersNumber() {
        return papersNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.papersNumber
     *
     * @param papersNumber the value for passenger.papersNumber
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public void setPapersNumber(String papersNumber) {
        this.papersNumber = papersNumber == null ? null : papersNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.unitsOrAddress
     *
     * @return the value of passenger.unitsOrAddress
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public String getUnitsOrAddress() {
        return unitsOrAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.unitsOrAddress
     *
     * @param unitsOrAddress the value for passenger.unitsOrAddress
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public void setUnitsOrAddress(String unitsOrAddress) {
        this.unitsOrAddress = unitsOrAddress == null ? null : unitsOrAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.thingReasonID
     *
     * @return the value of passenger.thingReasonID
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public String getThingReasonID() {
        return thingReasonID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.thingReasonID
     *
     * @param thingReasonID the value for passenger.thingReasonID
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public void setThingReasonID(String thingReasonID) {
        this.thingReasonID = thingReasonID == null ? null : thingReasonID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.thingReasonName
     *
     * @return the value of passenger.thingReasonName
     *
     * @mbg.generated Thu Apr 12 22:29:50 CST 2018
     */
    public String getThingReasonName() {
        return thingReasonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.thingReasonName
     *
     * @param thingReasonName the value for passenger.thingReasonName
     *
     * @mbg.generated Thu Apr 12 22:29:50 CST 2018
     */
    public void setThingReasonName(String thingReasonName) {
        this.thingReasonName = thingReasonName == null ? null : thingReasonName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.whereAreFrom
     *
     * @return the value of passenger.whereAreFrom
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public String getWhereAreFrom() {
        return whereAreFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.whereAreFrom
     *
     * @param whereAreFrom the value for passenger.whereAreFrom
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public void setWhereAreFrom(String whereAreFrom) {
        this.whereAreFrom = whereAreFrom == null ? null : whereAreFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.whereToGo
     *
     * @return the value of passenger.whereToGo
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public String getWhereToGo() {
        return whereToGo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.whereToGo
     *
     * @param whereToGo the value for passenger.whereToGo
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public void setWhereToGo(String whereToGo) {
        this.whereToGo = whereToGo == null ? null : whereToGo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.contactPhoneNumber
     *
     * @return the value of passenger.contactPhoneNumber
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public String getContactPhoneNumber() {
        return contactPhoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.contactPhoneNumber
     *
     * @param contactPhoneNumber the value for passenger.contactPhoneNumber
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public void setContactPhoneNumber(String contactPhoneNumber) {
        this.contactPhoneNumber = contactPhoneNumber == null ? null : contactPhoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.remarks
     *
     * @return the value of passenger.remarks
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.remarks
     *
     * @param remarks the value for passenger.remarks
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.del_flag
     *
     * @return the value of passenger.del_flag
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public Integer getDel_flag() {
        return del_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.del_flag
     *
     * @param del_flag the value for passenger.del_flag
     *
     * @mbg.generated Wed Apr 11 21:40:02 CST 2018
     */
    public void setDel_flag(Integer del_flag) {
        this.del_flag = del_flag;
    }


    @Override
    public String toString() {
        return "Passenger{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", genderID='" + genderID + '\'' +
                ", birthDate=" + birthDate +
                ", nationID='" + nationID + '\'' +
                ", licenceIssuingAuthorty='" + licenceIssuingAuthorty + '\'' +
                ", papersValidity=" + papersValidity +
                ", profession='" + profession + '\'' +
                ", educationDegreeID='" + educationDegreeID + '\'' +
                ", passengerLevelID='" + passengerLevelID + '\'' +
                ", papersID='" + papersID + '\'' +
                ", papersNumber='" + papersNumber + '\'' +
                ", unitsOrAddress='" + unitsOrAddress + '\'' +
                ", thingReasonID='" + thingReasonID + '\'' +
                ", whereAreFrom='" + whereAreFrom + '\'' +
                ", whereToGo='" + whereToGo + '\'' +
                ", contactPhoneNumber='" + contactPhoneNumber + '\'' +
                ", remarks='" + remarks + '\'' +
                ", del_flag=" + del_flag +
                '}';
    }
}