package com.cskaoyan.bean;

import java.util.Date;

public class Recepobject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recepobject.id
     *
     * @mbg.generated Wed Apr 11 19:41:45 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recepobject.targetTypeName
     *
     * @mbg.generated Wed Apr 11 19:41:45 CST 2018
     */
    private String targetTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recepobject.teamName
     *
     * @mbg.generated Wed Apr 11 19:41:45 CST 2018
     */
    private String teamName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recepobject.teamCode
     *
     * @mbg.generated Wed Apr 11 19:41:45 CST 2018
     */
    private String teamCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recepobject.principal
     *
     * @mbg.generated Wed Apr 11 19:41:45 CST 2018
     */
    private String principal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recepobject.registerTime
     *
     * @mbg.generated Wed Apr 11 19:41:45 CST 2018
     */
    private Date registerTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recepobject.contactPhoneNUmber
     *
     * @mbg.generated Wed Apr 11 19:41:45 CST 2018
     */
    private String contactPhoneNUmber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recepobject.id
     *
     * @return the value of recepobject.id
     *
     * @mbg.generated Wed Apr 11 19:41:45 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recepobject.id
     *
     * @param id the value for recepobject.id
     *
     * @mbg.generated Wed Apr 11 19:41:45 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recepobject.targetTypeName
     *
     * @return the value of recepobject.targetTypeName
     *
     * @mbg.generated Wed Apr 11 19:41:45 CST 2018
     */
    public String getTargetTypeName() {
        return targetTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recepobject.targetTypeName
     *
     * @param targetTypeName the value for recepobject.targetTypeName
     *
     * @mbg.generated Wed Apr 11 19:41:45 CST 2018
     */
    public void setTargetTypeName(String targetTypeName) {
        this.targetTypeName = targetTypeName == null ? null : targetTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recepobject.teamName
     *
     * @return the value of recepobject.teamName
     *
     * @mbg.generated Wed Apr 11 19:41:45 CST 2018
     */
    public String getTeamName() {
        return teamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recepobject.teamName
     *
     * @param teamName the value for recepobject.teamName
     *
     * @mbg.generated Wed Apr 11 19:41:45 CST 2018
     */
    public void setTeamName(String teamName) {
        this.teamName = teamName == null ? null : teamName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recepobject.teamCode
     *
     * @return the value of recepobject.teamCode
     *
     * @mbg.generated Wed Apr 11 19:41:45 CST 2018
     */
    public String getTeamCode() {
        return teamCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recepobject.teamCode
     *
     * @param teamCode the value for recepobject.teamCode
     *
     * @mbg.generated Wed Apr 11 19:41:45 CST 2018
     */
    public void setTeamCode(String teamCode) {
        this.teamCode = teamCode == null ? null : teamCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recepobject.principal
     *
     * @return the value of recepobject.principal
     *
     * @mbg.generated Wed Apr 11 19:41:45 CST 2018
     */
    public String getPrincipal() {
        return principal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recepobject.principal
     *
     * @param principal the value for recepobject.principal
     *
     * @mbg.generated Wed Apr 11 19:41:45 CST 2018
     */
    public void setPrincipal(String principal) {
        this.principal = principal == null ? null : principal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recepobject.registerTime
     *
     * @return the value of recepobject.registerTime
     *
     * @mbg.generated Wed Apr 11 19:41:45 CST 2018
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recepobject.registerTime
     *
     * @param registerTime the value for recepobject.registerTime
     *
     * @mbg.generated Wed Apr 11 19:41:45 CST 2018
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recepobject.contactPhoneNUmber
     *
     * @return the value of recepobject.contactPhoneNUmber
     *
     * @mbg.generated Wed Apr 11 19:41:45 CST 2018
     */
    public String getContactPhoneNUmber() {
        return contactPhoneNUmber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recepobject.contactPhoneNUmber
     *
     * @param contactPhoneNUmber the value for recepobject.contactPhoneNUmber
     *
     * @mbg.generated Wed Apr 11 19:41:45 CST 2018
     */
    public void setContactPhoneNUmber(String contactPhoneNUmber) {
        this.contactPhoneNUmber = contactPhoneNUmber;
    }

    @Override
    public String toString() {
        return "Recepobject{" +
                "id=" + id +
                ", targetTypeName='" + targetTypeName + '\'' +
                ", teamName='" + teamName + '\'' +
                ", teamCode='" + teamCode + '\'' +
                ", principal='" + principal + '\'' +
                ", registerTime=" + registerTime +
                ", contactPhoneNUmber=" + contactPhoneNUmber +
                '}';
    }
}