package com.cskaoyan.bean;

import java.util.Date;

public class Recepobject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recepobject.recepObjectId
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private Integer recepobjectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recepobject.recepObjectType
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private String recepobjecttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recepobject.recepbjectProcessPeople
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private String recepbjectprocesspeople;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recepobject.teamName
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private String teamname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recepobject.teamNumber
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private Integer teamnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recepobject.registerTime
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private Date registertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recepobject.contactPhone
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    private Integer contactphone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recepobject.recepObjectId
     *
     * @return the value of recepobject.recepObjectId
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public Integer getRecepobjectid() {
        return recepobjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recepobject.recepObjectId
     *
     * @param recepobjectid the value for recepobject.recepObjectId
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setRecepobjectid(Integer recepobjectid) {
        this.recepobjectid = recepobjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recepobject.recepObjectType
     *
     * @return the value of recepobject.recepObjectType
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public String getRecepobjecttype() {
        return recepobjecttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recepobject.recepObjectType
     *
     * @param recepobjecttype the value for recepobject.recepObjectType
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setRecepobjecttype(String recepobjecttype) {
        this.recepobjecttype = recepobjecttype == null ? null : recepobjecttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recepobject.recepbjectProcessPeople
     *
     * @return the value of recepobject.recepbjectProcessPeople
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public String getRecepbjectprocesspeople() {
        return recepbjectprocesspeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recepobject.recepbjectProcessPeople
     *
     * @param recepbjectprocesspeople the value for recepobject.recepbjectProcessPeople
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setRecepbjectprocesspeople(String recepbjectprocesspeople) {
        this.recepbjectprocesspeople = recepbjectprocesspeople == null ? null : recepbjectprocesspeople.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recepobject.teamName
     *
     * @return the value of recepobject.teamName
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public String getTeamname() {
        return teamname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recepobject.teamName
     *
     * @param teamname the value for recepobject.teamName
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setTeamname(String teamname) {
        this.teamname = teamname == null ? null : teamname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recepobject.teamNumber
     *
     * @return the value of recepobject.teamNumber
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public Integer getTeamnumber() {
        return teamnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recepobject.teamNumber
     *
     * @param teamnumber the value for recepobject.teamNumber
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setTeamnumber(Integer teamnumber) {
        this.teamnumber = teamnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recepobject.registerTime
     *
     * @return the value of recepobject.registerTime
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public Date getRegistertime() {
        return registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recepobject.registerTime
     *
     * @param registertime the value for recepobject.registerTime
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setRegistertime(Date registertime) {
        this.registertime = registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recepobject.contactPhone
     *
     * @return the value of recepobject.contactPhone
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public Integer getContactphone() {
        return contactphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recepobject.contactPhone
     *
     * @param contactphone the value for recepobject.contactPhone
     *
     * @mbg.generated Wed Apr 11 11:16:49 CST 2018
     */
    public void setContactphone(Integer contactphone) {
        this.contactphone = contactphone;
    }
}