package com.cskaoyan.bean;

public class Roomset {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomset.roomsetId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private String roomsetid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomset.roomsetTypeId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Integer roomsettypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomset.roomsetStatusId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Integer roomsetstatusid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomset.bedNum
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Integer bednum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomset.price
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Float price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomset.hourPrice
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Float hourprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomset.hourDurationLimit
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Integer hourdurationlimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomset.hourFirstDuration
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Float hourfirstduration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomset.hourPriceFirstTime
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Integer hourpricefirsttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomset.del_flag
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomset.roomsetId
     *
     * @return the value of roomset.roomsetId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public String getRoomsetid() {
        return roomsetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomset.roomsetId
     *
     * @param roomsetid the value for roomset.roomsetId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setRoomsetid(String roomsetid) {
        this.roomsetid = roomsetid == null ? null : roomsetid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomset.roomsetTypeId
     *
     * @return the value of roomset.roomsetTypeId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public Integer getRoomsettypeid() {
        return roomsettypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomset.roomsetTypeId
     *
     * @param roomsettypeid the value for roomset.roomsetTypeId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setRoomsettypeid(Integer roomsettypeid) {
        this.roomsettypeid = roomsettypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomset.roomsetStatusId
     *
     * @return the value of roomset.roomsetStatusId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public Integer getRoomsetstatusid() {
        return roomsetstatusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomset.roomsetStatusId
     *
     * @param roomsetstatusid the value for roomset.roomsetStatusId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setRoomsetstatusid(Integer roomsetstatusid) {
        this.roomsetstatusid = roomsetstatusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomset.bedNum
     *
     * @return the value of roomset.bedNum
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public Integer getBednum() {
        return bednum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomset.bedNum
     *
     * @param bednum the value for roomset.bedNum
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setBednum(Integer bednum) {
        this.bednum = bednum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomset.price
     *
     * @return the value of roomset.price
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomset.price
     *
     * @param price the value for roomset.price
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomset.hourPrice
     *
     * @return the value of roomset.hourPrice
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public Float getHourprice() {
        return hourprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomset.hourPrice
     *
     * @param hourprice the value for roomset.hourPrice
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setHourprice(Float hourprice) {
        this.hourprice = hourprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomset.hourDurationLimit
     *
     * @return the value of roomset.hourDurationLimit
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public Integer getHourdurationlimit() {
        return hourdurationlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomset.hourDurationLimit
     *
     * @param hourdurationlimit the value for roomset.hourDurationLimit
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setHourdurationlimit(Integer hourdurationlimit) {
        this.hourdurationlimit = hourdurationlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomset.hourFirstDuration
     *
     * @return the value of roomset.hourFirstDuration
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public Float getHourfirstduration() {
        return hourfirstduration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomset.hourFirstDuration
     *
     * @param hourfirstduration the value for roomset.hourFirstDuration
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setHourfirstduration(Float hourfirstduration) {
        this.hourfirstduration = hourfirstduration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomset.hourPriceFirstTime
     *
     * @return the value of roomset.hourPriceFirstTime
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public Integer getHourpricefirsttime() {
        return hourpricefirsttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomset.hourPriceFirstTime
     *
     * @param hourpricefirsttime the value for roomset.hourPriceFirstTime
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setHourpricefirsttime(Integer hourpricefirsttime) {
        this.hourpricefirsttime = hourpricefirsttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomset.del_flag
     *
     * @return the value of roomset.del_flag
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomset.del_flag
     *
     * @param delFlag the value for roomset.del_flag
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}