package com.cskaoyan.bean;

public class Roomsettype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomsettype.roomsetTypeId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Integer roomsettypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomsettype.roomsetTypeName
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private String roomsettypename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomsettype.del_flag
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomsettype.roomsetTypeId
     *
     * @return the value of roomsettype.roomsetTypeId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public Integer getRoomsettypeid() {
        return roomsettypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomsettype.roomsetTypeId
     *
     * @param roomsettypeid the value for roomsettype.roomsetTypeId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setRoomsettypeid(Integer roomsettypeid) {
        this.roomsettypeid = roomsettypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomsettype.roomsetTypeName
     *
     * @return the value of roomsettype.roomsetTypeName
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public String getRoomsettypename() {
        return roomsettypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomsettype.roomsetTypeName
     *
     * @param roomsettypename the value for roomsettype.roomsetTypeName
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setRoomsettypename(String roomsettypename) {
        this.roomsettypename = roomsettypename == null ? null : roomsettypename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomsettype.del_flag
     *
     * @return the value of roomsettype.del_flag
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomsettype.del_flag
     *
     * @param delFlag the value for roomsettype.del_flag
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}