package com.cskaoyan.bean;

public class Roomsetstatus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomsetstatus.roomsetStatusId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Integer roomsetstatusid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomsetstatus.del_flag
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomsetstatus.roomsetStatusName
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private byte[] roomsetstatusname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomsetstatus.roomsetStatusId
     *
     * @return the value of roomsetstatus.roomsetStatusId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public Integer getRoomsetstatusid() {
        return roomsetstatusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomsetstatus.roomsetStatusId
     *
     * @param roomsetstatusid the value for roomsetstatus.roomsetStatusId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setRoomsetstatusid(Integer roomsetstatusid) {
        this.roomsetstatusid = roomsetstatusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomsetstatus.del_flag
     *
     * @return the value of roomsetstatus.del_flag
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomsetstatus.del_flag
     *
     * @param delFlag the value for roomsetstatus.del_flag
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomsetstatus.roomsetStatusName
     *
     * @return the value of roomsetstatus.roomsetStatusName
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public byte[] getRoomsetstatusname() {
        return roomsetstatusname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomsetstatus.roomsetStatusName
     *
     * @param roomsetstatusname the value for roomsetstatus.roomsetStatusName
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setRoomsetstatusname(byte[] roomsetstatusname) {
        this.roomsetstatusname = roomsetstatusname;
    }
}