package com.cskaoyan.bean;

public class Roomset {

    private Integer id;

    /**
     * 客房新增 => 房间号
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private String roomNumber;

    /**
     * 客房新增 => 客房等级id
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Integer guestRoomLevelID;

    /**
     * 客房新增 => 房态id
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Integer roomStateID;

    /**
     * 客房新增 => 房态
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private String roomStateName;


    /**
     * 客房新增 => 客房等级
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private String guestRoomLevelName;

    /**
     * 客房新增 => 床位数
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Integer roomAmount;

    /**
     * 客房新增 => 标准房价/天
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Float standardPriceDay;

    /**
     * 钟点房设置 => 标准房价/小时
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Float standardPrice;

    /**
     * 钟点房设置 => 时长限制（小时）
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Integer maxDuration;

    /**
     * 钟点房设置 => 首段价格
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Float firstPrice;

    /**
     * 钟点房设置 => 首段时长（小时）
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Integer firstDuration;

    /**
     * 删除状态
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Integer del_flag;



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomset.roomsetId
     *
     * @return the value of roomset.roomsetId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public String getRoomNumber() {
        return roomNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomset.roomsetId
     *
     * @param roomNumber the value for roomset.roomsetId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setRoomNumber(String roomNumber) {
        this.roomNumber = roomNumber == null ? null : roomNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomset.roomsetTypeId
     *
     * @return the value of roomset.roomsetTypeId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public Integer getGuestRoomLevelID() {
        return guestRoomLevelID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomset.roomsetTypeId
     *
     * @param guestRoomLevelID the value for roomset.roomsetTypeId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setGuestRoomLevelID(Integer guestRoomLevelID) {
        this.guestRoomLevelID = guestRoomLevelID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomset.roomsetStatusId
     *
     * @return the value of roomset.roomsetStatusId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public Integer getRoomStateID() {
        return roomStateID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomset.roomsetStatusId
     *
     * @param roomStateID the value for roomset.roomsetStatusId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setRoomStateID(Integer roomStateID) {
        this.roomStateID = roomStateID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomset.bedNum
     *
     * @return the value of roomset.bedNum
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public Integer getBednum() {
        return roomAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomset.bedNum
     *
     * @param bednum the value for roomset.bedNum
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setBednum(Integer bednum) {
        this.roomAmount = bednum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomset.standardPriceDay
     *
     * @return the value of roomset.standardPriceDay
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public Float getStandardPriceDay() {
        return standardPriceDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomset.standardPriceDay
     *
     * @param standardPriceDay the value for roomset.standardPriceDay
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setStandardPriceDay(Float standardPriceDay) {
        this.standardPriceDay = standardPriceDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomset.hourPrice
     *
     * @return the value of roomset.hourPrice
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public Float getStandardPrice() {
        return standardPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomset.hourPrice
     *
     * @param standardPrice the value for roomset.hourPrice
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setStandardPrice(Float standardPrice) {
        this.standardPrice = standardPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomset.hourDurationLimit
     *
     * @return the value of roomset.hourDurationLimit
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public Integer getMaxDuration() {
        return maxDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomset.hourDurationLimit
     *
     * @param maxDuration the value for roomset.hourDurationLimit
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setMaxDuration(Integer maxDuration) {
        this.maxDuration = maxDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomset.hourFirstDuration
     *
     * @return the value of roomset.hourFirstDuration
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public Float getFirstPrice() {
        return firstPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomset.hourFirstDuration
     *
     * @param firstPrice the value for roomset.hourFirstDuration
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setFirstPrice(Float firstPrice) {
        this.firstPrice = firstPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomset.hourPriceFirstTime
     *
     * @return the value of roomset.hourPriceFirstTime
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public Integer getFirstDuration() {
        return firstDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomset.hourPriceFirstTime
     *
     * @param firstDuration the value for roomset.hourPriceFirstTime
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setFirstDuration(Integer firstDuration) {
        this.firstDuration = firstDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomset.del_flag
     *
     * @return the value of roomset.del_flag
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public Integer getDel_flag() {
        return del_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomset.del_flag
     *
     * @param del_flag the value for roomset.del_flag
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setDel_flag(Integer del_flag) {
        this.del_flag = del_flag;
    }

    public Integer getRoomAmount() {
        return roomAmount;
    }

    public void setRoomAmount(Integer roomAmount) {
        this.roomAmount = roomAmount;
    }

    public String getRoomStateName() {
        return roomStateName;
    }

    public void setRoomStateName(String roomStateName) {
        this.roomStateName = roomStateName;
    }

    public String getGuestRoomLevelName() {
        return guestRoomLevelName;
    }

    public void setGuestRoomLevelName(String guestRoomLevelName) {
        this.guestRoomLevelName = guestRoomLevelName;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
}

