package com.cskaoyan.bean;

import java.util.Date;

public class Tour {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour.tourId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Integer tourid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour.tourName
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private String tourname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour.tourSex
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private String toursex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour.tourBirthday
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Date tourbirthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour.tourNation
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private String tournation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour.tourIdentifyInstisution
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private String touridentifyinstisution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour.tourIdentifyValidDate
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Date touridentifyvaliddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour.tourRank
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private String tourrank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour.tourIdentifyType
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private String touridentifytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour.tourIdentifyNum
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Integer touridentifynum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour.tourCareer
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private String tourcareer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour.tourDegreeId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private String tourdegreeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour.tourAddress
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private String touraddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour.tourForPropose
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private String tourforpropose;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour.tourFromPlace
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private String tourfromplace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour.tourToPlace
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private String tourtoplace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour.tourContacePhone
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private Integer tourcontacephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tour.tourComment
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    private String tourcomment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour.tourId
     *
     * @return the value of tour.tourId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public Integer getTourid() {
        return tourid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour.tourId
     *
     * @param tourid the value for tour.tourId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setTourid(Integer tourid) {
        this.tourid = tourid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour.tourName
     *
     * @return the value of tour.tourName
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public String getTourname() {
        return tourname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour.tourName
     *
     * @param tourname the value for tour.tourName
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setTourname(String tourname) {
        this.tourname = tourname == null ? null : tourname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour.tourSex
     *
     * @return the value of tour.tourSex
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public String getToursex() {
        return toursex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour.tourSex
     *
     * @param toursex the value for tour.tourSex
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setToursex(String toursex) {
        this.toursex = toursex == null ? null : toursex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour.tourBirthday
     *
     * @return the value of tour.tourBirthday
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public Date getTourbirthday() {
        return tourbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour.tourBirthday
     *
     * @param tourbirthday the value for tour.tourBirthday
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setTourbirthday(Date tourbirthday) {
        this.tourbirthday = tourbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour.tourNation
     *
     * @return the value of tour.tourNation
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public String getTournation() {
        return tournation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour.tourNation
     *
     * @param tournation the value for tour.tourNation
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setTournation(String tournation) {
        this.tournation = tournation == null ? null : tournation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour.tourIdentifyInstisution
     *
     * @return the value of tour.tourIdentifyInstisution
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public String getTouridentifyinstisution() {
        return touridentifyinstisution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour.tourIdentifyInstisution
     *
     * @param touridentifyinstisution the value for tour.tourIdentifyInstisution
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setTouridentifyinstisution(String touridentifyinstisution) {
        this.touridentifyinstisution = touridentifyinstisution == null ? null : touridentifyinstisution.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour.tourIdentifyValidDate
     *
     * @return the value of tour.tourIdentifyValidDate
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public Date getTouridentifyvaliddate() {
        return touridentifyvaliddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour.tourIdentifyValidDate
     *
     * @param touridentifyvaliddate the value for tour.tourIdentifyValidDate
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setTouridentifyvaliddate(Date touridentifyvaliddate) {
        this.touridentifyvaliddate = touridentifyvaliddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour.tourRank
     *
     * @return the value of tour.tourRank
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public String getTourrank() {
        return tourrank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour.tourRank
     *
     * @param tourrank the value for tour.tourRank
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setTourrank(String tourrank) {
        this.tourrank = tourrank == null ? null : tourrank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour.tourIdentifyType
     *
     * @return the value of tour.tourIdentifyType
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public String getTouridentifytype() {
        return touridentifytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour.tourIdentifyType
     *
     * @param touridentifytype the value for tour.tourIdentifyType
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setTouridentifytype(String touridentifytype) {
        this.touridentifytype = touridentifytype == null ? null : touridentifytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour.tourIdentifyNum
     *
     * @return the value of tour.tourIdentifyNum
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public Integer getTouridentifynum() {
        return touridentifynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour.tourIdentifyNum
     *
     * @param touridentifynum the value for tour.tourIdentifyNum
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setTouridentifynum(Integer touridentifynum) {
        this.touridentifynum = touridentifynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour.tourCareer
     *
     * @return the value of tour.tourCareer
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public String getTourcareer() {
        return tourcareer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour.tourCareer
     *
     * @param tourcareer the value for tour.tourCareer
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setTourcareer(String tourcareer) {
        this.tourcareer = tourcareer == null ? null : tourcareer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour.tourDegreeId
     *
     * @return the value of tour.tourDegreeId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public String getTourdegreeid() {
        return tourdegreeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour.tourDegreeId
     *
     * @param tourdegreeid the value for tour.tourDegreeId
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setTourdegreeid(String tourdegreeid) {
        this.tourdegreeid = tourdegreeid == null ? null : tourdegreeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour.tourAddress
     *
     * @return the value of tour.tourAddress
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public String getTouraddress() {
        return touraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour.tourAddress
     *
     * @param touraddress the value for tour.tourAddress
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setTouraddress(String touraddress) {
        this.touraddress = touraddress == null ? null : touraddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour.tourForPropose
     *
     * @return the value of tour.tourForPropose
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public String getTourforpropose() {
        return tourforpropose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour.tourForPropose
     *
     * @param tourforpropose the value for tour.tourForPropose
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setTourforpropose(String tourforpropose) {
        this.tourforpropose = tourforpropose == null ? null : tourforpropose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour.tourFromPlace
     *
     * @return the value of tour.tourFromPlace
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public String getTourfromplace() {
        return tourfromplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour.tourFromPlace
     *
     * @param tourfromplace the value for tour.tourFromPlace
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setTourfromplace(String tourfromplace) {
        this.tourfromplace = tourfromplace == null ? null : tourfromplace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour.tourToPlace
     *
     * @return the value of tour.tourToPlace
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public String getTourtoplace() {
        return tourtoplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour.tourToPlace
     *
     * @param tourtoplace the value for tour.tourToPlace
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setTourtoplace(String tourtoplace) {
        this.tourtoplace = tourtoplace == null ? null : tourtoplace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour.tourContacePhone
     *
     * @return the value of tour.tourContacePhone
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public Integer getTourcontacephone() {
        return tourcontacephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour.tourContacePhone
     *
     * @param tourcontacephone the value for tour.tourContacePhone
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setTourcontacephone(Integer tourcontacephone) {
        this.tourcontacephone = tourcontacephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tour.tourComment
     *
     * @return the value of tour.tourComment
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public String getTourcomment() {
        return tourcomment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tour.tourComment
     *
     * @param tourcomment the value for tour.tourComment
     *
     * @mbg.generated Tue Apr 10 17:39:01 CST 2018
     */
    public void setTourcomment(String tourcomment) {
        this.tourcomment = tourcomment == null ? null : tourcomment.trim();
    }
}